### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'collapseSubtasks')

### ISSUE THREAD

**Issue by joshkel** [listr2/listr2#694]
### Replication of the Problem

Within the listr2 repository:

```
node_modules/.bin/ts-node examples/subtasks.example.ts
```

### Problem

Listr2 with subtasks may throw errors similar to the following:

```
[0] TypeError: Cannot read properties of undefined (reading 'collapseSubtasks')
[0]     at file:///Users/josh/src/node_modules/listr2/dist/index.js:914:65
[0]     at Array.some (<anonymous>)
[0]     at file:///Users/josh/src/node_modules/listr2/dist/index.js:914:23
[0]     at Array.flatMap (<anonymous>)
[0]     at _DefaultRenderer.renderer (file:///Users/josh/src/node_modules/listr2/dist/index.js:810:18)
[0]     at _DefaultRenderer.create (file:///Users/josh/src/node_modules/listr2/dist/index.js:713:30)
[0]     at _DefaultRenderer.update (file:///Users/josh/src/node_modules/listr2/dist/index.js:694:23)
[0]     at file:///Users/josh/src/node_modules/listr2/dist/index.js:686:14
[0]     at Timeout._onTimeout (file:///Users/josh/src/node_modules/listr2/dist/index.js:537:9)
[0]     at listOnTimeout (node:internal/timers:569:17)
```

I encountered this using [lint-staged](https://github.com/lint-staged/lint-staged) within [concurrently](https://www.npmjs.com/package/concurrently), but the same error can be seen by running listr2's substatsks example.

The error appears to be thrown [here](https://github.com/listr2/listr2/blob/842e2656e6d25fb7aeecbe23a74570751a475e8f/packages/listr2/src/renderer/default/renderer.ts#L406).

If I'm following the code correctly, a subtask's [rendererOptions](https://github.com/listr2/listr2/blob/842e2656e6d25fb7aeecbe23a74570751a475e8f/packages/listr2/src/lib/task.ts#L66) come from the Listr instance's [rendererClassOptions](https://github.com/listr2/listr2/blob/842e2656e6d25fb7aeecbe23a74570751a475e8f/packages/listr2/src/listr.ts#L93), which use an unsafe typecast and end up coming from the [rendererOptions or fallbackRendererOptions](https://github.com/listr2/listr2/blob/842e2656e6d25fb7aeecbe23a74570751a475e8f/packages/listr2/src/listr.ts#L85-L87) that are passed to the renderer - but neither of those are guaranteed to be set.

### Environment

operating system: macOS 14.0
Node.js:18.16.1
Terminal: iTerm2
listr2 version: observed in 7.0.1 and master

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @joshkel,

Thank you for reporting this, it is interesting that this kind of major bug has gone through the test suite.
