### ISSUE TITLE
[Bug]: [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by donmccurdy** [listr2/listr2#712]
### Replication of the Problem

In my application I've disabled `registerSignalListeners`, because <kbd>Ctrl</kbd>+<kbd>c</kbd> seemed not to work when it was enabled. That was working well enough, but in updating from 8.0.2 -> 8.2.0, the list execution has started failing.

A simplified example:

```typescript
// repl.ts
import { Listr, ListrTask } from 'listr2';

const tasks = [] as ListrTask[];
for (const name of ['a', 'b', 'c']) {
	tasks.push({
		title: name,
		task: async (ctx, task) => {
			let time = performance.now();
			await new Promise((resolve) => setTimeout(resolve, Math.random() * 100));
			time = Math.round(performance.now() - time);
			task.title = name.padEnd(20) + ` ${time.toFixed(1)}ms`;
		},
	});
}

await new Listr(tasks, { renderer: 'default', registerSignalListeners: false }).run();
```

```
npx tsx ./repl.ts
```

It also looks somewhat like the full list may be running twice before crashing, see sample output below.

### Problem

Setting `registerSignalListeners=false` breaks Listr2.

### Environment

- os: macOS Sonoma 14.4.1
- node: v20.10.0
- terminal: iTerm 2
- listr2: 8.2.0

### Log Output

```bash
➜  git:(main) ✗ npx tsx ./listr-test.ts
✔ a                    83.0ms
✔ b                    58.0ms
✔ c                    76.0ms
✔ a                    83.0ms
✔ b                    58.0ms
✔ c                    76.0ms
node:internal/validators:455
    throw new ERR_INVALID_ARG_TYPE(name, 'Function', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at __node_internal_ (node:internal/validators:455:11)
    at checkListener (node:events:274:3)
    at process.removeListener (node:events:677:7)
    at Listr.run (/Users/donmccurdy/Documents/Projects/$PROJECT/node_modules/listr2/dist/index.js:2236:17)
    at <anonymous> (/Users/donmccurdy/Documents/Projects/$PROJECT/listr-test.ts:16:1) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.10.0
```
```


### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by donmccurdy** [comment]
The fix is working for me, thank you @cenk1cenk2!
